export interface LanguageOption {
  value: string;
  label: string;
  region?: string;
}

export const MAX_TEXT_CHARACTERS = 500;

export const MAJOR_REGION_LANGUAGES: { [key: string]: LanguageOption[] } = {
  English: [
    { value: 'en-US', label: 'English (United States)', region: 'Americas' },
    { value: 'en-GB', label: 'English (United Kingdom)', region: 'Europe' },
    { value: 'en-AU', label: 'English (Australia)', region: 'Asia Pacific' },
    { value: 'en-CA', label: 'English (Canada)', region: 'Americas' },
    { value: 'en-HK', label: 'English (Hong Kong)', region: 'Asia Pacific' },
    { value: 'en-IE', label: 'English (Ireland)', region: 'Europe' },
    { value: 'en-IN', label: 'English (India)', region: 'Asia Pacific' },
    { value: 'en-KE', label: 'English (Kenya)', region: 'Africa' },
    { value: 'en-NG', label: 'English (Nigeria)', region: 'Africa' },
    { value: 'en-NZ', label: 'English (New Zealand)', region: 'Asia Pacific' },
    { value: 'en-PH', label: 'English (Philippines)', region: 'Asia Pacific' },
    { value: 'en-SG', label: 'English (Singapore)', region: 'Asia Pacific' },
    { value: 'en-TZ', label: 'English (Tanzania)', region: 'Africa' },
    { value: 'en-ZA', label: 'English (South Africa)', region: 'Africa' },
    { value: 'en-GH', label: 'English (Ghana)', region: 'Africa' },
  ],
  Spanish:[
    { value: 'es-ES', label: 'Spanish (Spain)', region: 'Europe' },
    { value: 'es-MX', label: 'Spanish (Mexico)', region: 'Americas' },
    { value: 'es-AR', label: 'Spanish (Argentina)', region: 'Americas' },
    { value: 'es-BO', label: 'Spanish (Bolivia)', region: 'Americas' },
    { value: 'es-CL', label: 'Spanish (Chile)', region: 'Americas' },
    { value: 'es-CO', label: 'Spanish (Colombia)', region: 'Americas' },
    { value: 'es-CR', label: 'Spanish (Costa Rica)', region: 'Americas' },
    { value: 'es-CU', label: 'Spanish (Cuba)', region: 'Americas' },
    { value: 'es-DO', label: 'Spanish (Dominican Republic)', region: 'Americas' },
    { value: 'es-EC', label: 'Spanish (Ecuador)', region: 'Americas' },
    { value: 'es-GT', label: 'Spanish (Guatemala)', region: 'Americas' },
    { value: 'es-HN', label: 'Spanish (Honduras)', region: 'Americas' },
    { value: 'es-NI', label: 'Spanish (Nicaragua)', region: 'Americas' },
    { value: 'es-PA', label: 'Spanish (Panama)', region: 'Americas' },
    { value: 'es-PE', label: 'Spanish (Peru)', region: 'Americas' },
    { value: 'es-PR', label: 'Spanish (Puerto Rico)', region: 'Americas' },
    { value: 'es-PY', label: 'Spanish (Paraguay)', region: 'Americas' },
    { value: 'es-SV', label: 'Spanish (El Salvador)', region: 'Americas' },
    { value: 'es-US', label: 'Spanish (United States)', region: 'Americas' },
    { value: 'es-UY', label: 'Spanish (Uruguay)', region: 'Americas' },
    { value: 'es-VE', label: 'Spanish (Venezuela)', region: 'Americas' },
  ],
  French:[
    { value: 'fr-FR', label: 'French (France)', region: 'Europe' },
    { value: 'fr-CA', label: 'French (Canada)', region: 'Americas' },
    { value: 'fr-CH', label: 'French (Switzerland)', region: 'Europe' },
  ],
  German:[
    { value: 'de-DE', label: 'German (Germany)', region: 'Europe' },
    { value: 'de-AT', label: 'German (Austria)', region: 'Europe' },
    { value: 'de-CH', label: 'German (Switzerland)', region: 'Europe' },
  ],
  Portuguese: [
    { value: "pt-BR", label: "Portuguese (Brazil)", region: "Americas" },
    { value: "pt-PT", label: "Portuguese (Portugal)", region: "Europe" },
  ],
  // arabic not supported pronunciation
  Arabic: [
    { value: 'ar-AE', label: 'Arabic (United Arab Emirates)', region: 'Middle East' },
    { value: 'ar-BH', label: 'Arabic (Bahrain)', region: 'Middle East' },
    { value: 'ar-DZ', label: 'Arabic (Algeria)', region: 'Middle East' },
    { value: 'ar-EG', label: 'Arabic (Egypt)', region: 'Middle East' },
    { value: 'ar-IL', label: 'Arabic (Israel)', region: 'Middle East' },
    { value: 'ar-IQ', label: 'Arabic (Iraq)', region: 'Middle East' },
    { value: 'ar-JO', label: 'Arabic (Jordan)', region: 'Middle East' },
    { value: 'ar-KW', label: 'Arabic (Kuwait)', region: 'Middle East' },
    { value: 'ar-LB', label: 'Arabic (Lebanon)', region: 'Middle East' },
    { value: 'ar-LY', label: 'Arabic (Libya)', region: 'Middle East' },
    { value: 'ar-MA', label: 'Arabic (Morocco)', region: 'Middle East' },
    { value: 'ar-OM', label: 'Arabic (Oman)', region: 'Middle East' },
    { value: 'ar-PS', label: 'Arabic (Palestinian Authority)', region: 'Middle East' },
    { value: 'ar-QA', label: 'Arabic (Qatar)', region: 'Middle East' },
    { value: 'ar-SA', label: 'Arabic (Saudi Arabia)', region: 'Middle East' },
    { value: 'ar-SY', label: 'Arabic (Syria)', region: 'Middle East' },
    { value: 'ar-TN', label: 'Arabic (Tunisia)', region: 'Middle East' },
    { value: 'ar-YE', label: 'Arabic (Yemen)', region: 'Middle East' },
  ],
};

export const PRONUNCIATION_LANGUAGES: LanguageOption[] = [
  // English variants (most comprehensive support)
  { value: 'en-US', label: 'English (United States)', region: 'Americas' },
  { value: 'en-GB', label: 'English (United Kingdom)', region: 'Europe' },
  { value: 'en-AU', label: 'English (Australia)', region: 'Asia Pacific' },
  { value: 'en-CA', label: 'English (Canada)', region: 'Americas' },
  { value: 'en-HK', label: 'English (Hong Kong)', region: 'Asia Pacific' },
  { value: 'en-IE', label: 'English (Ireland)', region: 'Europe' },
  { value: 'en-IN', label: 'English (India)', region: 'Asia Pacific' },
  { value: 'en-KE', label: 'English (Kenya)', region: 'Africa' },
  { value: 'en-NG', label: 'English (Nigeria)', region: 'Africa' },
  { value: 'en-NZ', label: 'English (New Zealand)', region: 'Asia Pacific' },
  { value: 'en-PH', label: 'English (Philippines)', region: 'Asia Pacific' },
  { value: 'en-SG', label: 'English (Singapore)', region: 'Asia Pacific' },
  { value: 'en-TZ', label: 'English (Tanzania)', region: 'Africa' },
  { value: 'en-ZA', label: 'English (South Africa)', region: 'Africa' },
  { value: 'en-GH', label: 'English (Ghana)', region: 'Africa' },

  // Spanish variants
  { value: 'es-ES', label: 'Spanish (Spain)', region: 'Europe' },
  { value: 'es-MX', label: 'Spanish (Mexico)', region: 'Americas' },
  { value: 'es-AR', label: 'Spanish (Argentina)', region: 'Americas' },
  { value: 'es-BO', label: 'Spanish (Bolivia)', region: 'Americas' },
  { value: 'es-CL', label: 'Spanish (Chile)', region: 'Americas' },
  { value: 'es-CO', label: 'Spanish (Colombia)', region: 'Americas' },
  { value: 'es-CR', label: 'Spanish (Costa Rica)', region: 'Americas' },
  { value: 'es-CU', label: 'Spanish (Cuba)', region: 'Americas' },
  { value: 'es-DO', label: 'Spanish (Dominican Republic)', region: 'Americas' },
  { value: 'es-EC', label: 'Spanish (Ecuador)', region: 'Americas' },
  { value: 'es-GT', label: 'Spanish (Guatemala)', region: 'Americas' },
  { value: 'es-HN', label: 'Spanish (Honduras)', region: 'Americas' },
  { value: 'es-NI', label: 'Spanish (Nicaragua)', region: 'Americas' },
  { value: 'es-PA', label: 'Spanish (Panama)', region: 'Americas' },
  { value: 'es-PE', label: 'Spanish (Peru)', region: 'Americas' },
  { value: 'es-PR', label: 'Spanish (Puerto Rico)', region: 'Americas' },
  { value: 'es-PY', label: 'Spanish (Paraguay)', region: 'Americas' },
  { value: 'es-SV', label: 'Spanish (El Salvador)', region: 'Americas' },
  { value: 'es-US', label: 'Spanish (United States)', region: 'Americas' },
  { value: 'es-UY', label: 'Spanish (Uruguay)', region: 'Americas' },
  { value: 'es-VE', label: 'Spanish (Venezuela)', region: 'Americas' },

  // French variants
  { value: 'fr-FR', label: 'French (France)', region: 'Europe' },
  { value: 'fr-CA', label: 'French (Canada)', region: 'Americas' },
  { value: 'fr-CH', label: 'French (Switzerland)', region: 'Europe' },

  // German variants
  { value: 'de-DE', label: 'German (Germany)', region: 'Europe' },
  { value: 'de-AT', label: 'German (Austria)', region: 'Europe' },
  { value: 'de-CH', label: 'German (Switzerland)', region: 'Europe' },

  // Other major languages with pronunciation support
  { value: 'it-IT', label: 'Italian (Italy)', region: 'Europe' },
  { value: 'pt-BR', label: 'Portuguese (Brazil)', region: 'Americas' },
  { value: 'pt-PT', label: 'Portuguese (Portugal)', region: 'Europe' },
  { value: 'ja-JP', label: 'Japanese (Japan)', region: 'Asia Pacific' },
  { value: 'ko-KR', label: 'Korean (South Korea)', region: 'Asia Pacific' },
  { value: 'zh-CN', label: 'Chinese (Mandarin, Simplified)', region: 'Asia Pacific' },
  { value: 'ru-RU', label: 'Russian (Russia)', region: 'Europe' },
  { value: 'ar-SA', label: 'Arabic (Saudi Arabia)', region: 'Middle East' },
  { value: 'hi-IN', label: 'Hindi (India)', region: 'Asia Pacific' },

  // Additional languages with pronunciation support
  { value: 'nl-NL', label: 'Dutch (Netherlands)', region: 'Europe' },
  { value: 'pl-PL', label: 'Polish (Poland)', region: 'Europe' },
  { value: 'sv-SE', label: 'Swedish (Sweden)', region: 'Europe' },
  { value: 'da-DK', label: 'Danish (Denmark)', region: 'Europe' },
  { value: 'fi-FI', label: 'Finnish (Finland)', region: 'Europe' },
  { value: 'cs-CZ', label: 'Czech (Czech Republic)', region: 'Europe' },
  { value: 'hu-HU', label: 'Hungarian (Hungary)', region: 'Europe' },
  { value: 'ro-RO', label: 'Romanian (Romania)', region: 'Europe' },
  { value: 'sk-SK', label: 'Slovak (Slovakia)', region: 'Europe' },
  { value: 'sl-SI', label: 'Slovenian (Slovenia)', region: 'Europe' },
  { value: 'hr-HR', label: 'Croatian (Croatia)', region: 'Europe' },
  { value: 'et-EE', label: 'Estonian (Estonia)', region: 'Europe' },
  { value: 'lv-LV', label: 'Latvian (Latvia)', region: 'Europe' },
  { value: 'lt-LT', label: 'Lithuanian (Lithuania)', region: 'Europe' },
  { value: 'ca-ES', label: 'Catalan (Spain)', region: 'Europe' },
  { value: 'fil-PH', label: 'Filipino (Philippines)', region: 'Asia Pacific' },
  { value: 'ga-IE', label: 'Irish (Ireland)', region: 'Europe' },
  { value: 'id-ID', label: 'Indonesian (Indonesia)', region: 'Asia Pacific' },
  { value: 'th-TH', label: 'Thai (Thailand)', region: 'Asia Pacific' },
];

// SPEECH-TO-TEXT & TEXT-TO-SPEECH - Most comprehensive language support
// Based on Azure Speech Service speech-to-text capabilities
export const SPEECH_LANGUAGES: LanguageOption[] = [
  // African languages
  { value: 'af-ZA', label: 'Afrikaans (South Africa)', region: 'Africa' },
  { value: 'am-ET', label: 'Amharic (Ethiopia)', region: 'Africa' },
  { value: 'sw-KE', label: 'Kiswahili (Kenya)', region: 'Africa' },
  { value: 'sw-TZ', label: 'Kiswahili (Tanzania)', region: 'Africa' },
  { value: 'zu-ZA', label: 'isiZulu (South Africa)', region: 'Africa' },
  { value: 'so-SO', label: 'Somali (Somalia)', region: 'Africa' },

  // Arabic variants
  { value: 'ar-AE', label: 'Arabic (United Arab Emirates)', region: 'Middle East' },
  { value: 'ar-BH', label: 'Arabic (Bahrain)', region: 'Middle East' },
  { value: 'ar-DZ', label: 'Arabic (Algeria)', region: 'Middle East' },
  { value: 'ar-EG', label: 'Arabic (Egypt)', region: 'Middle East' },
  { value: 'ar-IL', label: 'Arabic (Israel)', region: 'Middle East' },
  { value: 'ar-IQ', label: 'Arabic (Iraq)', region: 'Middle East' },
  { value: 'ar-JO', label: 'Arabic (Jordan)', region: 'Middle East' },
  { value: 'ar-KW', label: 'Arabic (Kuwait)', region: 'Middle East' },
  { value: 'ar-LB', label: 'Arabic (Lebanon)', region: 'Middle East' },
  { value: 'ar-LY', label: 'Arabic (Libya)', region: 'Middle East' },
  { value: 'ar-MA', label: 'Arabic (Morocco)', region: 'Middle East' },
  { value: 'ar-OM', label: 'Arabic (Oman)', region: 'Middle East' },
  { value: 'ar-PS', label: 'Arabic (Palestinian Authority)', region: 'Middle East' },
  { value: 'ar-QA', label: 'Arabic (Qatar)', region: 'Middle East' },
  { value: 'ar-SA', label: 'Arabic (Saudi Arabia)', region: 'Middle East' },
  { value: 'ar-SY', label: 'Arabic (Syria)', region: 'Middle East' },
  { value: 'ar-TN', label: 'Arabic (Tunisia)', region: 'Middle East' },
  { value: 'ar-YE', label: 'Arabic (Yemen)', region: 'Middle East' },

  // Asian languages
  { value: 'as-IN', label: 'Assamese (India)', region: 'Asia Pacific' },
  { value: 'az-AZ', label: 'Azerbaijani (Azerbaijan)', region: 'Asia Pacific' },
  { value: 'bn-IN', label: 'Bengali (India)', region: 'Asia Pacific' },
  { value: 'gu-IN', label: 'Gujarati (India)', region: 'Asia Pacific' },
  { value: 'hi-IN', label: 'Hindi (India)', region: 'Asia Pacific' },
  { value: 'id-ID', label: 'Indonesian (Indonesia)', region: 'Asia Pacific' },
  { value: 'ja-JP', label: 'Japanese (Japan)', region: 'Asia Pacific' },
  { value: 'jv-ID', label: 'Javanese (Indonesia)', region: 'Asia Pacific' },
  { value: 'ka-GE', label: 'Georgian (Georgia)', region: 'Asia Pacific' },
  { value: 'kk-KZ', label: 'Kazakh (Kazakhstan)', region: 'Asia Pacific' },
  { value: 'km-KH', label: 'Khmer (Cambodia)', region: 'Asia Pacific' },
  { value: 'kn-IN', label: 'Kannada (India)', region: 'Asia Pacific' },
  { value: 'ko-KR', label: 'Korean (South Korea)', region: 'Asia Pacific' },
  { value: 'lo-LA', label: 'Lao (Laos)', region: 'Asia Pacific' },
  { value: 'ml-IN', label: 'Malayalam (India)', region: 'Asia Pacific' },
  { value: 'mn-MN', label: 'Mongolian (Mongolia)', region: 'Asia Pacific' },
  { value: 'mr-IN', label: 'Marathi (India)', region: 'Asia Pacific' },
  { value: 'ms-MY', label: 'Malay (Malaysia)', region: 'Asia Pacific' },
  { value: 'my-MM', label: 'Burmese (Myanmar)', region: 'Asia Pacific' },
  { value: 'ne-NP', label: 'Nepali (Nepal)', region: 'Asia Pacific' },
  { value: 'or-IN', label: 'Odia (India)', region: 'Asia Pacific' },
  { value: 'pa-IN', label: 'Punjabi (India)', region: 'Asia Pacific' },
  { value: 'si-LK', label: 'Sinhala (Sri Lanka)', region: 'Asia Pacific' },
  { value: 'ta-IN', label: 'Tamil (India)', region: 'Asia Pacific' },
  { value: 'te-IN', label: 'Telugu (India)', region: 'Asia Pacific' },
  { value: 'th-TH', label: 'Thai (Thailand)', region: 'Asia Pacific' },
  { value: 'ur-IN', label: 'Urdu (India)', region: 'Asia Pacific' },
  { value: 'vi-VN', label: 'Vietnamese (Vietnam)', region: 'Asia Pacific' },

  // Chinese variants
  { value: 'zh-CN', label: 'Chinese (Mandarin, Simplified)', region: 'Asia Pacific' },
  { value: 'zh-HK', label: 'Chinese (Cantonese, Traditional)', region: 'Asia Pacific' },
  { value: 'zh-TW', label: 'Chinese (Taiwanese Mandarin)', region: 'Asia Pacific' },
  { value: 'wuu-CN', label: 'Chinese (Wu, Simplified)', region: 'Asia Pacific' },
  { value: 'yue-CN', label: 'Chinese (Cantonese, Simplified)', region: 'Asia Pacific' },
  { value: 'zh-CN-shandong', label: 'Chinese (Jilu Mandarin)', region: 'Asia Pacific' },
  { value: 'zh-CN-sichuan', label: 'Chinese (Southwestern Mandarin)', region: 'Asia Pacific' },

  // English variants
  { value: 'en-AU', label: 'English (Australia)', region: 'Asia Pacific' },
  { value: 'en-CA', label: 'English (Canada)', region: 'Americas' },
  { value: 'en-GB', label: 'English (United Kingdom)', region: 'Europe' },
  { value: 'en-GH', label: 'English (Ghana)', region: 'Africa' },
  { value: 'en-HK', label: 'English (Hong Kong)', region: 'Asia Pacific' },
  { value: 'en-IE', label: 'English (Ireland)', region: 'Europe' },
  { value: 'en-IN', label: 'English (India)', region: 'Asia Pacific' },
  { value: 'en-KE', label: 'English (Kenya)', region: 'Africa' },
  { value: 'en-NG', label: 'English (Nigeria)', region: 'Africa' },
  { value: 'en-NZ', label: 'English (New Zealand)', region: 'Asia Pacific' },
  { value: 'en-PH', label: 'English (Philippines)', region: 'Asia Pacific' },
  { value: 'en-SG', label: 'English (Singapore)', region: 'Asia Pacific' },
  { value: 'en-TZ', label: 'English (Tanzania)', region: 'Africa' },
  { value: 'en-US', label: 'English (United States)', region: 'Americas' },
  { value: 'en-ZA', label: 'English (South Africa)', region: 'Africa' },

  // European languages
  { value: 'bg-BG', label: 'Bulgarian (Bulgaria)', region: 'Europe' },
  { value: 'bs-BA', label: 'Bosnian (Bosnia)', region: 'Europe' },
  { value: 'ca-ES', label: 'Catalan (Spain)', region: 'Europe' },
  { value: 'cs-CZ', label: 'Czech (Czech Republic)', region: 'Europe' },
  { value: 'cy-GB', label: 'Welsh (United Kingdom)', region: 'Europe' },
  { value: 'da-DK', label: 'Danish (Denmark)', region: 'Europe' },
  { value: 'de-AT', label: 'German (Austria)', region: 'Europe' },
  { value: 'de-CH', label: 'German (Switzerland)', region: 'Europe' },
  { value: 'de-DE', label: 'German (Germany)', region: 'Europe' },
  { value: 'el-GR', label: 'Greek (Greece)', region: 'Europe' },
  { value: 'et-EE', label: 'Estonian (Estonia)', region: 'Europe' },
  { value: 'eu-ES', label: 'Basque (Spain)', region: 'Europe' },
  { value: 'fi-FI', label: 'Finnish (Finland)', region: 'Europe' },
  { value: 'fr-BE', label: 'French (Belgium)', region: 'Europe' },
  { value: 'fr-CA', label: 'French (Canada)', region: 'Americas' },
  { value: 'fr-CH', label: 'French (Switzerland)', region: 'Europe' },
  { value: 'fr-FR', label: 'French (France)', region: 'Europe' },
  { value: 'ga-IE', label: 'Irish (Ireland)', region: 'Europe' },
  { value: 'gl-ES', label: 'Galician (Spain)', region: 'Europe' },
  { value: 'he-IL', label: 'Hebrew (Israel)', region: 'Middle East' },
  { value: 'hr-HR', label: 'Croatian (Croatia)', region: 'Europe' },
  { value: 'hu-HU', label: 'Hungarian (Hungary)', region: 'Europe' },
  { value: 'hy-AM', label: 'Armenian (Armenia)', region: 'Europe' },
  { value: 'is-IS', label: 'Icelandic (Iceland)', region: 'Europe' },
  { value: 'it-CH', label: 'Italian (Switzerland)', region: 'Europe' },
  { value: 'it-IT', label: 'Italian (Italy)', region: 'Europe' },
  { value: 'lt-LT', label: 'Lithuanian (Lithuania)', region: 'Europe' },
  { value: 'lv-LV', label: 'Latvian (Latvia)', region: 'Europe' },
  { value: 'mk-MK', label: 'Macedonian (North Macedonia)', region: 'Europe' },
  { value: 'mt-MT', label: 'Maltese (Malta)', region: 'Europe' },
  { value: 'nb-NO', label: 'Norwegian Bokmål (Norway)', region: 'Europe' },
  { value: 'nl-BE', label: 'Dutch (Belgium)', region: 'Europe' },
  { value: 'nl-NL', label: 'Dutch (Netherlands)', region: 'Europe' },
  { value: 'pl-PL', label: 'Polish (Poland)', region: 'Europe' },
  { value: 'pt-BR', label: 'Portuguese (Brazil)', region: 'Americas' },
  { value: 'pt-PT', label: 'Portuguese (Portugal)', region: 'Europe' },
  { value: 'ro-RO', label: 'Romanian (Romania)', region: 'Europe' },
  { value: 'ru-RU', label: 'Russian (Russia)', region: 'Europe' },
  { value: 'sk-SK', label: 'Slovak (Slovakia)', region: 'Europe' },
  { value: 'sl-SI', label: 'Slovenian (Slovenia)', region: 'Europe' },
  { value: 'sq-AL', label: 'Albanian (Albania)', region: 'Europe' },
  { value: 'sr-RS', label: 'Serbian (Serbia)', region: 'Europe' },
  { value: 'sv-SE', label: 'Swedish (Sweden)', region: 'Europe' },
  { value: 'tr-TR', label: 'Turkish (Turkey)', region: 'Europe' },
  { value: 'uk-UA', label: 'Ukrainian (Ukraine)', region: 'Europe' },

  // Other languages
  { value: 'fa-IR', label: 'Persian (Iran)', region: 'Middle East' },
  { value: 'fil-PH', label: 'Filipino (Philippines)', region: 'Asia Pacific' },
  { value: 'ps-AF', label: 'Pashto (Afghanistan)', region: 'Asia Pacific' },
  { value: 'uz-UZ', label: 'Uzbek (Uzbekistan)', region: 'Asia Pacific' },

  // Spanish variants
  { value: 'es-AR', label: 'Spanish (Argentina)', region: 'Americas' },
  { value: 'es-BO', label: 'Spanish (Bolivia)', region: 'Americas' },
  { value: 'es-CL', label: 'Spanish (Chile)', region: 'Americas' },
  { value: 'es-CO', label: 'Spanish (Colombia)', region: 'Americas' },
  { value: 'es-CR', label: 'Spanish (Costa Rica)', region: 'Americas' },
  { value: 'es-CU', label: 'Spanish (Cuba)', region: 'Americas' },
  { value: 'es-DO', label: 'Spanish (Dominican Republic)', region: 'Americas' },
  { value: 'es-EC', label: 'Spanish (Ecuador)', region: 'Americas' },
  { value: 'es-ES', label: 'Spanish (Spain)', region: 'Europe' },
  { value: 'es-GQ', label: 'Spanish (Equatorial Guinea)', region: 'Africa' },
  { value: 'es-GT', label: 'Spanish (Guatemala)', region: 'Americas' },
  { value: 'es-HN', label: 'Spanish (Honduras)', region: 'Americas' },
  { value: 'es-MX', label: 'Spanish (Mexico)', region: 'Americas' },
  { value: 'es-NI', label: 'Spanish (Nicaragua)', region: 'Americas' },
  { value: 'es-PA', label: 'Spanish (Panama)', region: 'Americas' },
  { value: 'es-PE', label: 'Spanish (Peru)', region: 'Americas' },
  { value: 'es-PR', label: 'Spanish (Puerto Rico)', region: 'Americas' },
  { value: 'es-PY', label: 'Spanish (Paraguay)', region: 'Americas' },
  { value: 'es-SV', label: 'Spanish (El Salvador)', region: 'Americas' },
  { value: 'es-US', label: 'Spanish (United States)', region: 'Americas' },
  { value: 'es-UY', label: 'Spanish (Uruguay)', region: 'Americas' },
  { value: 'es-VE', label: 'Spanish (Venezuela)', region: 'Americas' },
];

// TRANSLATION - Azure Translator supported languages
// Based on Azure AI Translator service capabilities
export const TRANSLATION_LANGUAGES: LanguageOption[] = [
  { value: 'af', label: 'Afrikaans' },
  { value: 'am', label: 'Amharic' },
  { value: 'ar', label: 'Arabic' },
  { value: 'as', label: 'Assamese' },
  { value: 'az', label: 'Azerbaijani' },
  { value: 'ba', label: 'Bashkir' },
  { value: 'be', label: 'Belarusian' },
  { value: 'bg', label: 'Bulgarian' },
  { value: 'bho', label: 'Bhojpuri' },
  { value: 'bn', label: 'Bengali' },
  { value: 'bo', label: 'Tibetan' },
  { value: 'brx', label: 'Bodo' },
  { value: 'bs', label: 'Bosnian' },
  { value: 'ca', label: 'Catalan' },
  { value: 'cs', label: 'Czech' },
  { value: 'cy', label: 'Welsh' },
  { value: 'da', label: 'Danish' },
  { value: 'de', label: 'German' },
  { value: 'doi', label: 'Dogri' },
  { value: 'dsb', label: 'Lower Sorbian' },
  { value: 'dv', label: 'Divehi' },
  { value: 'el', label: 'Greek' },
  { value: 'en', label: 'English' },
  { value: 'es', label: 'Spanish' },
  { value: 'et', label: 'Estonian' },
  { value: 'eu', label: 'Basque' },
  { value: 'fa', label: 'Persian' },
  { value: 'fi', label: 'Finnish' },
  { value: 'fil', label: 'Filipino' },
  { value: 'fj', label: 'Fijian' },
  { value: 'fo', label: 'Faroese' },
  { value: 'fr', label: 'French' },
  { value: 'fr-CA', label: 'French (Canada)' },
  { value: 'fy', label: 'Western Frisian' },
  { value: 'ga', label: 'Irish' },
  { value: 'gd', label: 'Scottish Gaelic' },
  { value: 'gl', label: 'Galician' },
  { value: 'gom', label: 'Konkani' },
  { value: 'gu', label: 'Gujarati' },
  { value: 'ha', label: 'Hausa' },
  { value: 'he', label: 'Hebrew' },
  { value: 'hi', label: 'Hindi' },
  { value: 'hne', label: 'Chhattisgarhi' },
  { value: 'hr', label: 'Croatian' },
  { value: 'hsb', label: 'Upper Sorbian' },
  { value: 'ht', label: 'Haitian Creole' },
  { value: 'hu', label: 'Hungarian' },
  { value: 'hy', label: 'Armenian' },
  { value: 'id', label: 'Indonesian' },
  { value: 'ig', label: 'Igbo' },
  { value: 'ikt', label: 'Inuinnaqtun' },
  { value: 'is', label: 'Icelandic' },
  { value: 'it', label: 'Italian' },
  { value: 'iu', label: 'Inuktitut' },
  { value: 'iu-Latn', label: 'Inuktitut (Latin)' },
  { value: 'ja', label: 'Japanese' },
  { value: 'ka', label: 'Georgian' },
  { value: 'kk', label: 'Kazakh' },
  { value: 'km', label: 'Khmer' },
  { value: 'kmr', label: 'Kurdish (Northern)' },
  { value: 'kn', label: 'Kannada' },
  { value: 'ko', label: 'Korean' },
  { value: 'ks', label: 'Kashmiri' },
  { value: 'ku', label: 'Kurdish (Central)' },
  { value: 'ky', label: 'Kyrgyz' },
  { value: 'ln', label: 'Lingala' },
  { value: 'lo', label: 'Lao' },
  { value: 'lt', label: 'Lithuanian' },
  { value: 'lug', label: 'Luganda' },
  { value: 'lv', label: 'Latvian' },
  { value: 'lzh', label: 'Chinese (Literary)' },
  { value: 'mai', label: 'Maithili' },
  { value: 'mg', label: 'Malagasy' },
  { value: 'mi', label: 'Māori' },
  { value: 'mk', label: 'Macedonian' },
  { value: 'ml', label: 'Malayalam' },
  { value: 'mn-Cyrl', label: 'Mongolian (Cyrillic)' },
  { value: 'mn-Mong', label: 'Mongolian (Traditional)' },
  { value: 'mni', label: 'Manipuri' },
  { value: 'mr', label: 'Marathi' },
  { value: 'ms', label: 'Malay' },
  { value: 'mt', label: 'Maltese' },
  { value: 'mww', label: 'Hmong Daw' },
  { value: 'my', label: 'Myanmar (Burmese)' },
  { value: 'nb', label: 'Norwegian' },
  { value: 'ne', label: 'Nepali' },
  { value: 'nl', label: 'Dutch' },
  { value: 'nso', label: 'Sepedi' },
  { value: 'nya', label: 'Nyanja' },
  { value: 'or', label: 'Odia' },
  { value: 'otq', label: 'Querétaro Otomi' },
  { value: 'pa', label: 'Punjabi' },
  { value: 'pl', label: 'Polish' },
  { value: 'prs', label: 'Dari' },
  { value: 'ps', label: 'Pashto' },
  { value: 'pt', label: 'Portuguese (Brazil)' },
  { value: 'pt-PT', label: 'Portuguese (Portugal)' },
  { value: 'ro', label: 'Romanian' },
  { value: 'ru', label: 'Russian' },
  { value: 'run', label: 'Rundi' },
  { value: 'rw', label: 'Kinyarwanda' },
  { value: 'sat', label: 'Santali' },
  { value: 'sd', label: 'Sindhi' },
  { value: 'si', label: 'Sinhala' },
  { value: 'sk', label: 'Slovak' },
  { value: 'sl', label: 'Slovenian' },
  { value: 'sm', label: 'Samoan' },
  { value: 'sn', label: 'Shona' },
  { value: 'so', label: 'Somali' },
  { value: 'sq', label: 'Albanian' },
  { value: 'sr-Cyrl', label: 'Serbian (Cyrillic)' },
  { value: 'sr-Latn', label: 'Serbian (Latin)' },
  { value: 'st', label: 'Sesotho' },
  { value: 'sv', label: 'Swedish' },
  { value: 'sw', label: 'Swahili' },
  { value: 'ta', label: 'Tamil' },
  { value: 'te', label: 'Telugu' },
  { value: 'th', label: 'Thai' },
  { value: 'ti', label: 'Tigrinya' },
  { value: 'tk', label: 'Turkmen' },
  { value: 'tlh-Latn', label: 'Klingon (Latin)' },
  { value: 'tlh-Piqd', label: 'Klingon (pIqaD)' },
  { value: 'tn', label: 'Setswana' },
  { value: 'to', label: 'Tongan' },
  { value: 'tr', label: 'Turkish' },
  { value: 'tt', label: 'Tatar' },
  { value: 'ty', label: 'Tahitian' },
  { value: 'ug', label: 'Uyghur' },
  { value: 'uk', label: 'Ukrainian' },
  { value: 'ur', label: 'Urdu' },
  { value: 'uz', label: 'Uzbek (Latin)' },
  { value: 've', label: 'Venda' },
  { value: 'vi', label: 'Vietnamese' },
  { value: 'xh', label: 'Xhosa' },
  { value: 'yo', label: 'Yoruba' },
  { value: 'yua', label: 'Yucatec Maya' },
  { value: 'yue', label: 'Cantonese (Traditional)' },
  { value: 'zh-Hans', label: 'Chinese Simplified' },
  { value: 'zh-Hant', label: 'Chinese Traditional' },
  { value: 'zu', label: 'Zulu' },
];

export const REGIONS = ["Americas", "Europe", "Asia Pacific", "Middle East", "Africa"];

// Helper functions to get languages by specific criteria
export const getLanguagesByRegion = (languages: LanguageOption[], region: string): LanguageOption[]=> {
  return languages.filter(lang => lang.region === region);
};

export const getLanguageLabelByValue = (languages: LanguageOption[], value: string): LanguageOption | undefined => {
  return languages.find(lang => lang.value === value);
}

export const getProsodySupportedLanguages = (): string[] => {
  return ['en-US']; // Currently only en-US supports prosody assessment
};

export const getFastTranscriptionLanguages = (): string[] => {
  // Languages that support fast transcription based on Azure documentation
  return [
    'ar-SA', 'da-DK', 'de-AT', 'de-CH', 'de-DE', 'en-GB', 'en-IN', 'en-US',
    'es-ES', 'es-MX', 'fi-FI', 'fr-FR', 'he-IL', 'hi-IN', 'id-ID', 'it-IT',
    'ja-JP', 'ko-KR', 'nl-NL', 'pl-PL', 'pt-BR', 'pt-PT', 'ru-RU', 'sv-SE',
    'th-TH', 'zh-CN'
  ];
};

export const getCustomSpeechSupportedLanguages = (): string[] => {
  // Languages with comprehensive custom speech support (Audio + human-labeled transcript)
  return [
    'ar-AE', 'ar-BH', 'ar-DZ', 'ar-EG', 'ar-IL', 'ar-IQ', 'ar-JO', 'ar-KW',
    'ar-LB', 'ar-LY', 'ar-MA', 'ar-OM', 'ar-PS', 'ar-QA', 'ar-SA', 'ar-SY',
    'ar-TN', 'ar-YE', 'as-IN', 'cs-CZ', 'da-DK', 'de-AT', 'de-CH', 'de-DE',
    'el-GR', 'en-AU', 'en-CA', 'en-GB', 'en-GH', 'en-HK', 'en-IE', 'en-IN',
    'en-KE', 'en-NG', 'en-NZ', 'en-PH', 'en-SG', 'en-TZ', 'en-US', 'en-ZA',
    'es-BO', 'es-CL', 'es-CO', 'es-CR', 'es-EC', 'es-ES', 'es-GQ', 'es-GT',
    'es-HN', 'es-MX', 'es-NI', 'es-PA', 'es-PE', 'es-PR', 'es-PY', 'es-SV',
    'es-UY', 'es-VE', 'fi-FI', 'fr-FR', 'he-IL', 'hi-IN', 'hu-HU', 'id-ID',
    'it-IT', 'ja-JP', 'ko-KR', 'nl-NL', 'or-IN', 'pa-IN', 'pl-PL', 'pt-BR',
    'pt-PT', 'ru-RU', 'sv-SE', 'ta-IN', 'te-IN', 'th-TH', 'tr-TR', 'uk-UA',
    'ur-IN', 'zh-CN', 'zh-HK', 'zh-TW'
  ];
};

// Language groups for easier selection
export const LANGUAGE_GROUPS = {
  ENGLISH: SPEECH_LANGUAGES.filter(lang => lang.value.startsWith('en-')),
  SPANISH: SPEECH_LANGUAGES.filter(lang => lang.value.startsWith('es-')),
  ARABIC: SPEECH_LANGUAGES.filter(lang => lang.value.startsWith('ar-')),
  CHINESE: SPEECH_LANGUAGES.filter(lang => lang.value.startsWith('zh-') || lang.value.includes('wuu-') || lang.value.includes('yue-')),
  FRENCH: SPEECH_LANGUAGES.filter(lang => lang.value.startsWith('fr-')),
  GERMAN: SPEECH_LANGUAGES.filter(lang => lang.value.startsWith('de-')),
  PORTUGUESE: SPEECH_LANGUAGES.filter(lang => lang.value.startsWith('pt-')),
};

// Most commonly used languages for quick access
export const POPULAR_LANGUAGES: LanguageOption[] = [
  { value: 'en-US', label: 'English (United States)', region: 'Americas' },
  { value: 'en-GB', label: 'English (United Kingdom)', region: 'Europe' },
  { value: 'es-ES', label: 'Spanish (Spain)', region: 'Europe' },
  { value: 'es-MX', label: 'Spanish (Mexico)', region: 'Americas' },
  { value: 'fr-FR', label: 'French (France)', region: 'Europe' },
  { value: 'de-DE', label: 'German (Germany)', region: 'Europe' },
  { value: 'it-IT', label: 'Italian (Italy)', region: 'Europe' },
  { value: 'pt-BR', label: 'Portuguese (Brazil)', region: 'Americas' },
  { value: 'ja-JP', label: 'Japanese (Japan)', region: 'Asia Pacific' },
  { value: 'ko-KR', label: 'Korean (South Korea)', region: 'Asia Pacific' },
  { value: 'zh-CN', label: 'Chinese (Mandarin, Simplified)', region: 'Asia Pacific' },
  { value: 'ru-RU', label: 'Russian (Russia)', region: 'Europe' },
  { value: 'ar-SA', label: 'Arabic (Saudi Arabia)', region: 'Middle East' },
  { value: 'hi-IN', label: 'Hindi (India)', region: 'Asia Pacific' },
];